### PR TITLE
Don't specify body on editable element

### PR DESCRIPTION
**Pull request by timwis**
The readme suggests you enable this module via `makeEditable(document.body)`, which doesn't work because of this line (it expects `makeEditable(document)`). I would expect, however, that the module doesn't _need_ to be applied to `document.body` but can be applied to any node (like a `<div>`). So I'd propose this change. (Note that the variable name `doc` would perhaps be better written as `el`)

### CODE REVIEW

**Comment by TehShrike** [comment]
I agree.  [`contentEditable` is on all `HTMLElement`s](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable).

There should be another test asserting this behavior (and I'm guessing the existing test will need changed as well).

Would you be willing to change the test?  If not, I'll hopefully get to it eventually (maybe this week).

**Comment by timwis** [comment]
Sure thing. I'll do my best to do that this week.

**Comment by timwis** [comment]
Bah! looks like this is a no-go, as [`execCommand`](https://github.com/npm-dom/make-editable/blob/9afedac95a153f04b1e4a6076790c1fc59ffa0ec/index.js#L38) can only be executed on a `document` node.

Sounds like the option is to (a) require the user pass a reference to `document` when enabling make-editable, (b) traverse the element's node tree to find its containing document (using something like `assert` to ensure it exists or error out if it doesn't), or (c) leave the current functionality and fix the documentation (remove `.body` from the example).

On a separate note [this is a pretty cool demo](http://codepen.io/netsi1964/pen/QbLLGW?editors=0010) of the Web API. Hadn't come across this functionality before.

**Comment by TehShrike** [comment]
aah, ok, that makes some kind of sense.

Option a seems like the straightest path forward.  I'll edit the readme real quick.

Thanks for reporting this and figuring it out!

**Pull request closed without merging**
